# Generated by Django 4.2.7 on 2023-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_rename_comment_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Personal", "Personal"),
                    ("Work", "Work"),
                    ("School", "School"),
                    ("Coding", "Coding"),
                ],
                default="Personal",
                max_length=10,
            ),
        ),
    ]
