# Generated by Django 4.2.7 on 2023-11-10 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_alter_todo_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="tag_color",
        ),
    ]
