# Generated by Django 4.2.7 on 2023-11-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_remove_todo_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
